### ISSUE TITLE
Crash with GregTech when generate new chunks

### ISSUE THREAD

**Issue by GordonHollow** [octarine-noise/BetterFoliage#106]
Minecraft 1.10.2, Forge 2122, BetterFoliage latest version, Gregtech 5.10.06
When i generated new chunks - game crashes, without BetterFoliage - no crash

I think its cause Gregtech and BetterFoliage use the same method to attach additional texture on block (BetterFoliage bettergrass and gregtech ore)

PM
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at net.minecraft.world.World.func_175690_a(World.java:2451)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
	at net.minecraft.world.ChunkCache.func_190300_a(ChunkCache.java:74)
	at net.minecraft.world.ChunkCache.func_175625_s(ChunkCache.java:64)
	at ChunkCacheOF.func_175625_s(ChunkCacheOF.java:184)
	**at mods.betterfoliage.client.integration.ForestryLeavesSupport.get(ForestryIntegration.kt:102)
	at mods.betterfoliage.client.texture.LeafRegistry.get(LeafRegistry.kt:66)
	at mods.betterfoliage.client.texture.LeafRegistry.get(LeafRegistry.kt:68)
	at mods.betterfoliage.client.render.RenderLeaves.isEligible(RenderLeaves.kt:44)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)**
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

**Comment by 0Navis0** [comment]
It's not linked to GregTech, I get this crash even when GregTech isn't present. http://pastebin.com/zeBJvEwL

**Comment by GordonHollow** [comment]
So...it's BetterFoliage issue, but with my modlist a can play with BetterFoliage until adding GregTech
With GregTech - needed choose GT or BetterFoliage, with single one - all work good

**Comment by 0Navis0** [comment]
I never installed GregTech and I still get the issue.

**Comment by octarine-noise** [comment]
Should be fixed in 2.1.2

Please drop a comment if the problem persists.

**Comment by GordonHollow** [comment]
Yes, fixed.
