### ISSUE TITLE
Crash/Batching Chunks

### ISSUE THREAD

**Issue by Xuerian** [octarine-noise/BetterFoliage#108]
I've seen similar descriptions in a couple issues, but none specifically matched this. Sorry if it's a duplicate.

```
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at mods.betterfoliage.client.render.RenderLeaves.render(RenderLeaves.kt:51)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:90)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

I'm not using GT or OptiFine, I am using BOP.

**Comment by octarine-noise** [comment]
Should be fixed in 2.1.2

Please drop a comment if the problem persists.

**Comment by Xuerian** [comment]
Seems to work, though now I have to report to FoamFix that it makes all the BetterFoliage textures purple.

**Comment by DanielMckibbin** [comment]
Having this exact issue when Extra Utilities (1.1.3a) is enabled. As soon as it's disabled the issue goes away.

Using version 2.1.3. 

[crash-2016-12-22_06.06.11-client.txt](https://github.com/octarine-noise/BetterFoliage/files/668110/crash-2016-12-22_06.06.11-client.txt)
