### ISSUE TITLE
not Server Compat?

### ISSUE THREAD

**Issue by O13SC3N3** [octarine-noise/BetterFoliage#16]
1.7.10 forge 1291 java 8

Tried all versions from 1.0.6 to current, and server won't boot.

**Comment by O13SC3N3** [comment]
[15:59:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception while updating neighbours
	at net.minecraft.world.World.func_147460_e(World.java:730) ~[ahb.class:?]
	at net.minecraft.world.World.func_147459_d(World.java:651) ~[ahb.class:?]
	at net.minecraft.world.World.func_147444_c(World.java:613) ~[ahb.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488) ~[ahb.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:466) ~[ahb.class:?]
	at thaumcraft.common.lib.world.WorldGenMound.generate2(WorldGenMound.java:2114) ~[WorldGenMound.class:?]
	at thaumcraft.common.lib.world.WorldGenMound.func_76484_a(WorldGenMound.java:1572) ~[WorldGenMound.class:?]
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateSurface(ThaumcraftWorldGenerator.java:395) ~[ThaumcraftWorldGenerator.class:?]
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:109) ~[ThaumcraftWorldGenerator.class:?]
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:95) ~[ThaumcraftWorldGenerator.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) ~[GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
	at fastcraft.a.c.a(F:84) ~[FASTCRAFT-1.19.jar:?]
	at fastcraft.Hooks.r(F:139) ~[FASTCRAFT-1.19.jar:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:235) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: mods/betterfoliage/client/render/IRenderBlockDecorator
	at net.minecraft.block.Block.func_149710_n(Block.java:187) ~[aji.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:771) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:764) ~[ahb.class:?]
	at net.minecraft.world.World.func_72801_o(World.java:1014) ~[ahb.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.getBlockPathWeight(EntityCreatureBase.java:1294) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.naturalSpawnCheck(EntityCreatureBase.java:501) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.spawnCheck(EntityCreatureBase.java:441) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70601_bi(EntityCreatureBase.java:409) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBase.spawnMobs(SpawnTypeBase.java:516) ~[SpawnTypeBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBlockBreak.spawnMobs(SpawnTypeBlockBreak.java:27) ~[SpawnTypeBlockBreak.class:?]
	at lycanite.lycanitesmobs.api.spawning.CustomSpawner.onHarvestDrops(CustomSpawner.java:176) ~[CustomSpawner.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_415_CustomSpawner_onHarvestDrops_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.func_149690_a(Block.java:656) ~[aji.class:?]
	at net.minecraft.block.Block.func_149697_b(Block.java:648) ~[aji.class:?]
	at net.minecraft.block.BlockBush.func_149855_e(BlockBush.java:58) ~[ajr.class:?]
	at net.minecraft.block.BlockBush.func_149695_a(BlockBush.java:46) ~[ajr.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:697) ~[ahb.class:?]
	... 22 more
Caused by: java.lang.ClassNotFoundException: mods.betterfoliage.client.render.IRenderBlockDecorator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149710_n(Block.java:187) ~[aji.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:771) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:764) ~[ahb.class:?]
	at net.minecraft.world.World.func_72801_o(World.java:1014) ~[ahb.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.getBlockPathWeight(EntityCreatureBase.java:1294) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.naturalSpawnCheck(EntityCreatureBase.java:501) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.spawnCheck(EntityCreatureBase.java:441) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70601_bi(EntityCreatureBase.java:409) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBase.spawnMobs(SpawnTypeBase.java:516) ~[SpawnTypeBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBlockBreak.spawnMobs(SpawnTypeBlockBreak.java:27) ~[SpawnTypeBlockBreak.class:?]
	at lycanite.lycanitesmobs.api.spawning.CustomSpawner.onHarvestDrops(CustomSpawner.java:176) ~[CustomSpawner.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_415_CustomSpawner_onHarvestDrops_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.func_149690_a(Block.java:656) ~[aji.class:?]
	at net.minecraft.block.Block.func_149697_b(Block.java:648) ~[aji.class:?]
	at net.minecraft.block.BlockBush.func_149855_e(BlockBush.java:58) ~[ajr.class:?]
	at net.minecraft.block.BlockBush.func_149695_a(BlockBush.java:46) ~[ajr.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:697) ~[ahb.class:?]
	... 22 more
Caused by: java.lang.RuntimeException: Attempted to load class mods/betterfoliage/client/render/IRenderBlockDecorator for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.2.1291-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149710_n(Block.java:187) ~[aji.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:771) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:764) ~[ahb.class:?]
	at net.minecraft.world.World.func_72801_o(World.java:1014) ~[ahb.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.getBlockPathWeight(EntityCreatureBase.java:1294) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.naturalSpawnCheck(EntityCreatureBase.java:501) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.spawnCheck(EntityCreatureBase.java:441) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70601_bi(EntityCreatureBase.java:409) ~[EntityCreatureBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBase.spawnMobs(SpawnTypeBase.java:516) ~[SpawnTypeBase.class:?]
	at lycanite.lycanitesmobs.api.spawning.SpawnTypeBlockBreak.spawnMobs(SpawnTypeBlockBreak.java:27) ~[SpawnTypeBlockBreak.class:?]
	at lycanite.lycanitesmobs.api.spawning.CustomSpawner.onHarvestDrops(CustomSpawner.java:176) ~[CustomSpawner.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_415_CustomSpawner_onHarvestDrops_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.func_149690_a(Block.java:656) ~[aji.class:?]
	at net.minecraft.block.Block.func_149697_b(Block.java:648) ~[aji.class:?]
	at net.minecraft.block.BlockBush.func_149855_e(BlockBush.java:58) ~[ajr.class:?]
	at net.minecraft.block.BlockBush.func_149695_a(BlockBush.java:46) ~[ajr.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:697) ~[ahb.class:?]

**Comment by kerenon** [comment]
BetterFoliage is a client mod. You don't need to install it onto the server.

**Comment by octarine-noise** [comment]
Forgot to update this. Fixed in 1.1.3 and 1.0.10

It's not needed on the server, but if the server operator leaves it in the mods directory (for whatever resaon), it's nice if it doesn't crash.
