### ISSUE TITLE
BetterFoliage-MC1.12-2.2.0 crash on start

### ISSUE THREAD

**Issue by Tsoccerguy3** [octarine-noise/BetterFoliage#213]
BetterFoliage-MC1.12-2.2.0  crash on start as only mod installed
Forge 1.12.2 build 2759
log:

[12:42:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:42:53] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2759 for Minecraft 1.12.2 loading
[12:42:53] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_192, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_192
[12:42:53] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[12:42:53] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[12:42:53] [main/INFO] [FML]: Searching C:\Users\ASUS\AppData\Roaming\.minecraft\mods for mods
[12:42:53] [main/INFO] [FML]: Searching C:\Users\ASUS\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[12:42:53] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[12:42:53] [main/WARN] [FML]: The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
[12:42:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:42:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:42:54] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[12:42:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:42:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:42:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: kotlin/reflect/KDeclarationContainer
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at mods.betterfoliage.loader.Refs.<clinit>(Refs.kt:13)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at mods.betterfoliage.loader.BetterFoliageTransformer.<init>(BetterFoliageCore.kt:13)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at $wrapper.mods.betterfoliage.loader.BetterFoliageTransformer.<init>(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KDeclarationContainer
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:42:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 18 more

**Comment by octarine-noise** [comment]
You didn't install Forgelin. I even wrote it in red :)
