### ISSUE TITLE
[1.10.2] pink textures for generated grass

### ISSUE THREAD

**Issue by xemnes** [octarine-noise/BetterFoliage#236]
im not exactly sure whats causing it, but i feel it might be to do with this
`[18:04:01] [Client thread/ERROR]: Unable to parse metadata from bf_gen_grass:textures/|dom=minecraft|path=textures/blocks/tallgrass|snowed=false|generate.png
java.lang.RuntimeException: invalid frameindex 1
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188539_a(TextureAtlasSprite.java:394) ~[bwe.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_184397_a(TextureMap.java:473) [bwd.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:342) [bwd.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:156) [bwd.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:04:01] [Client thread/ERROR]: Unable to parse metadata from bf_gen_grass:textures/|dom=minecraft|path=textures/blocks/tallgrass|snowed=true|generate.png
java.lang.RuntimeException: invalid frameindex 1
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188539_a(TextureAtlasSprite.java:394) ~[bwe.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_184397_a(TextureMap.java:473) [bwd.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:342) [bwd.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:156) [bwd.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

turned off use generted textures, but this error still appears regardless when reloading a resource pack. id like to get rid of the error completely.
seems to be something to do with an mcmeta file that acompanies an animation? though my grass in my resource pack is just a regular 32x32 texture

**Comment by xemnes** [comment]
managed to fix it, was rather odd...
so i use the conquest reforged mod in my pack and it has a built in resource pack inside the mod jar. tallgrass.png in the pack is animated, acompanied with a mcmeta file for it.
my custom resource pack does not have an animated tallgrass texture.
minecraft is loading in the mcmeta from the conquest resource pack regardless so i created an mcmeta for my static texture with no data inside it and it fixed the problem.
