### ISSUE TITLE
[1.12.2] Crash on singleplay when world finished load

### ISSUE THREAD

**Issue by Orygeunik** [octarine-noise/BetterFoliage#267]
When single play world finished load, game will be crashed.
[Log (full)](https://gist.github.com/Orygeunik/9b7ecb6d2b9c9b5e769661f5ffaf1e13)

Log (trimmed)
``` log
java.lang.NoSuchMethodException: net.optifine.render.RenderEnv.<init>(net.minecraft.block.state.IBlockState, net.minecraft.util.math.BlockPos)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at mods.betterfoliage.client.integration.OptifineRenderEnv.<init>(OptifineCustomColors.kt:50)
	at mods.betterfoliage.client.integration.OptifineCustomColors$renderEnv$2.invoke(OptifineCustomColors.kt:36)
	at mods.betterfoliage.client.integration.OptifineCustomColors$renderEnv$2.invoke(OptifineCustomColors.kt:26)
	at mods.octarinecore.Utils$sam$java_util_function_Supplier$0.get(Utils.kt)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source)
	at java.lang.ThreadLocal.setInitialValue(Unknown Source)
	at java.lang.ThreadLocal.get(Unknown Source)
	at mods.octarinecore.ThreadLocalDelegate.getValue(Utils.kt:60)
	at mods.betterfoliage.client.integration.OptifineCustomColors.getRenderEnv(OptifineCustomColors.kt)
	at mods.betterfoliage.client.integration.OptifineCustomColors.getBlockColor(OptifineCustomColors.kt:41)
	at mods.betterfoliage.client.render.RenderGrass.render(RenderGrass.kt:73)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:89)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

When mod rollback to "BetterFoliage-MC1.12-2.2.0.jar" - problem solved

MC 1.12.2
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)

List of mods
``` Text
minecraft                  | 1.12.2                  
mcp                        | 9.42                    
FML                        | 8.0.99.99               
forge                      | 14.23.5.2847            
ivtoolkit                  | 1.3.3-1.12              
opencomputers|core         | 1.7.5.192               
buildcraftlib              | 7.99.24.4               
buildcraftcore             | 7.99.24.4               
buildcraftfactory          | 7.99.24.4               
buildcrafttransport        | 7.99.24.4               
buildcraftsilicon          | 7.99.24.4               
additionalpipes            | 6.0.0.8                 
ctm                        | MC1.12.2-1.0.1.30       
appliedenergistics2        | rv6-stable-7            
architecturecraft          | @VERSION@               
jei                        | 4.15.0.293              
quark                      | r1.6-177                
autoreglib                 | 1.3-32                  
babyanimals                | 1.11-3                  
baubles                    | 1.5.2                   
betteranimalsplus          | 8.1.1                   
forgelin                   | 1.8.4                   
betterfoliage              | 2.3.1                   
betternether               | 0.1.8.4                 
bibliocraft                | 2.4.5                   
blockdrops                 | 1.4.0                   
buildcraftbuilders         | 7.99.24.4               
crafttweaker               | 4.1.19                  
buildcraftenergy           | 7.99.24.4               
ic2                        | 2.8.188-ex112           
forestry                   | 5.8.2.409               
tesla                      | 1.0.63                  
theoneprobe                | 1.4.28                  
buildcraftcompat           | 7.99.24.4               
buildcraftrobotics         | 7.99.24.4               
champions                  | 1.12.2-1.0.11.2         
mysticalworld              | 1.12.2-1.6.1            
chisel                     | MC1.12.2-1.0.1.44       
chiselsandbits             | 14.33                   
codechickenlib             | 3.2.3.358               
mantle                     | 1.12-1.3.3.55           
twilightforest             | 3.10.1013               
tconstruct                 | 1.12.2-2.13.0.171       
conarm                     | 1.2.5.3                 
ctgui                      | 1.0.0                   
crafttweakerjei            | 2.0.3                   
cyclopscore                | 1.5.1                   
defiledlands               | 1.4.3                   
orelib                     | 3.6.0.1                 
dsurround                  | 3.6.0.2                 
eggs                       | 1.0                     
enderzoo                   | 1.12.1-1.4.0.49         
railcraft                  | 12.0.0                  
immersiveengineering       | 0.12-92                 
engineersdoors             | 0.8.0                   
evilcraft                  | 0.10.78                 
evilcraftcompat            | 1.0.0                   
waila                      | 1.8.26                  
extracells                 | 2.6.5                   
fbp                        | 2.4.1                   
mod_lavacow                | 1.0.11                  
forgemultipartcbe          | 2.6.2.83                
microblockcbe              | 2.6.2.83                
minecraftmultipartcbe      | 2.6.2.83                
fw                         | 1.6.0                   
cfm                        | 6.3.1                   
globalxp                   | v1.4.10                 
instantunify               | 1.1.2                   
inventorytweaks            | 1.64+dev.150.7168e7a    
ironchest                  | 1.12.2-7.0.67.844       
jeibees                    | 0.9.0.5                 
journeymap                 | 1.12.2-5.5.6            
jeresources                | 0.9.2.60                
letmesleep                 | 1.2.1                   
levelup2                   | ${version}              
malisiscore                | 1.12.2-6.5.1-SNAPSHOT   
malisisdoors               | 1.12.2-7.3.0            
mcmultipart                | 2.5.3                   
mcwbridges                 | 1.0                     
mcwroofs                   | 1.0.1                   
moartinkers                | 0.6.0                   
monstertotems              | @VERSION@               
mrtjpcore                  | 2.1.4.43                
opencomputers              | 1.7.5.192               
patchouli                  | 1.0-20                  
projectred-core            | 4.9.4.120               
projectred-compat          | 1.0                     
projectred-integration     | 4.9.4.120               
projectred-transmission    | 4.9.4.120               
projectred-fabrication     | 4.9.4.120               
projectred-illumination    | 4.9.4.120               
projectred-expansion       | 4.9.4.120               
projectred-relocation      | 4.9.4.120               
projectred-transportation  | 4.9.4.120               
projectred-exploration     | 4.9.4.120               
reccomplex                 | 1.4.8.2                 
redstoneflux               | 2.1.0                   
additionalstructures       | 2.3.1                   
roguelike                  | 1.8.0                   
srparasites                | 1.3.0                   
swampland                  | 2.6                     
tcomplement                | 1.12.2-0.4.3            
tinkerscompendium          | 1.4.2.31                
tinkersjei                 | 1.2                     
tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769
tlauncher_custom_cape_skin | 1.4                     
traverse                   | 1.6.0                   
treechopper                | 1.2.4                   
wanionlib                  | 1.12.2-2.4              
wawla                      | 2.5.273                 
dshuds                     | 3.6.0.0                 
industrialwires            | 1.7-36                  
mysticallib                | 1.12.2-1.4.0            
unidict                    | 1.12.2-2.9.3            

````

**Comment by octarine-noise** [comment]
The version of BF and Optifine you are using are incompatible. You can either:
 - switch to BF 2.3.0 (it's the same otherwise)
 - switch to Optifine F4 (or newer)

**Comment by Orygeunik** [comment]
Please, write this conditions on page's mod. Thx
