### ISSUE TITLE
[1.14.4] Crash with [Placeable items] mod

### ISSUE THREAD

**Issue by AlpZz80** [octarine-noise/BetterFoliage#286]
**-Issue-**

[MULTIPLAYER] Instant crashing when loading chunks that contains one or many placeable items.

**-Versions-**

Minecraft : 1.14.4
Forge : 1.14.4-28.2.1
BetterFoliage : 2.5.0
Kottle : 1.4.0

**-Crash Report-**

---- Minecraft Crash Report ----
// Don't do that.
 
Time: 2/17/20 2:15 PM
Description: Tesselating block model
 
java.lang.NullPointerException: Tesselating block model
    at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348) ~[?:?] {re:classloading}
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88) ~[?:?] {re:classloading}
    at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
    at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
    at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
    at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
    at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
    at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
    at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.getQuads(ModelLoader.java:348)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88)
 
-- Block model being tesselated --
Details:
    Block: Block{placeableitems:book_block}[rotation=10]
    Block location: World: (1174,68,-4491), Chunk: (at 6,4,5 in 73,-281; contains blocks 1168,0,-4496 to 1183,255,-4481), Region: (2,-9; contains chunks 64,-288 to 95,-257, blocks 1024,0,-4608 to 1535,255,-4097)
    Using AO: true
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95)
 
-- Block being tesselated --
Details:
    Block: Block{placeableitems:book_block}[rotation=10]
    Block location: World: (1174,68,-4491), Chunk: (at 6,4,5 in 73,-281; contains blocks 1168,0,-4496 to 1183,255,-4481), Region: (2,-9; contains chunks 64,-288 to 95,-257, blocks 1024,0,-4608 to 1535,255,-4097)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89)
    at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
    at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
    at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
    at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015)
 
-- Affected level --
Details:
    All players: 2 total; [ClientPlayerEntity['AlpZz'/572, l='MpServer', x=1186.01, y=55.00, z=-4524.52], RemoteClientPlayerEntity['Teuchone'/244, l='MpServer', x=1186.01, y=77.50, z=-4524.52]]
    Chunk stats: Client Chunk Cache: 1521, 1241
    Level dimension: DimensionType{minecraft:overworld}
    Level name: MpServer
    Level seed: 0
    Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
    Level generator options: {}
    Level spawn location: World: (69,80,-115), Chunk: (at 5,5,13 in 4,-8; contains blocks 64,0,-128 to 79,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 97247046 game time, 1000 day time
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Server brand: forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:45)
    at java.lang.Thread.run(Thread.java:745)
 
-- System Details --
Details:
    Minecraft Version: 1.14.4
    Minecraft Version ID: 1.14.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2072244744 bytes (1976 MB) / 4892655616 bytes (4666 MB) up to 5594677248 bytes (5335 MB)
    CPUs: 8
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6001m -Xms256m -XX:PermSize=256m
    ModLauncher: 4.1.0+62+5bfa59b
    ModLauncher launch target: fmlclient
    ModLauncher naming: srg
    ModLauncher services:
        /eventbus-1.0.0-service.jar eventbus PLUGINSERVICE
        /forge-1.14.4-28.2.1.jar object_holder_definalize PLUGINSERVICE
        /forge-1.14.4-28.2.1.jar runtime_enum_extender PLUGINSERVICE
        /accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE
        /forge-1.14.4-28.2.1.jar capability_inject_definalize PLUGINSERVICE
        /forge-1.14.4-28.2.1.jar runtimedistcleaner PLUGINSERVICE
        /OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE
        /forge-1.14.4-28.2.1.jar fml TRANSFORMATIONSERVICE
        /MixinBootstrap-1.0.0.jar mixinbootstrap TRANSFORMATIONSERVICE
        /MixinBootstrap-1.0.0.jar mixin PLUGINSERVICE
        /MixinBootstrap-1.0.0.jar mixinbootstrap PLUGINSERVICE
    FML: 28.2
    Forge: net.minecraftforge:28.2.1
    FML Language Providers:
        javafml@28.2
        minecraft@1
        kotlinfml@1.4.0
    Mod List:
        forge-1.14.4-28.2.1-client.jar Minecraft {minecraft@1.14.4 DONE}
        simply_trophies-1.0-1.14.4.jar Simple Trophies {simple_trophies@1.0-1.14.4 DONE}
        Mortar-1.1.1.jar Mortar {mortar@1.1.1 DONE}
        embellishcraft-1.14.4-1.3.1.jar EmbellishCraft {embellishcraft@1.14.4-1.3.1 DONE}
        simpleportals-1.14.4-1.6.0.2.jar Simple Portals {simpleportals@1.14.4-1.6.0.2 DONE}
        illuminations-0.1.0-1.14.4.jar Illuminations for Forge {illuminations@1.0.0.0 DONE}
        BiomesOPlenty-1.14.4-9.0.0.261-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
        Wyrmroost-1.14.4-1.0.2.jar Wyrmroost {wyrmroost@1.0.2 DONE}
        jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
        extcaves-1.4.2.jar Extended Caves {extcaves@1.4.2 DONE}
        simplefarming-1.14.4-1.2.4.jar Simple Farming {simplefarming@1.14.4-1.2.4 DONE}
        embellishcraft-bop-1.14.4-1.0.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.14.4-1.0.0 DONE}
        FloristV1.1.4.jar Florist {florist@1.1.4 DONE}
        Xaeros_Minimap_1.19.2_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.2 DONE}
        AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
        XaerosWorldMap_1.5.2_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.2 DONE}
        placeableitems-4.0.0.jar Placeable Items {placeableitems@4.0 DONE}
        extlights-1.7.jar Extended Lights {extlights@1.7 DONE}
        citadel-1.0.0.jar Citadel {citadel@1.0.0 DONE}
        betteranimals-1.14.4-5.2.1.jar Cyber's Better Animal Models {betteranimals@5.2.1 DONE}
        SereneSeasons-1.14.4-2.0.0.9-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.9 DONE}
        backpacked-1.2.0-1.14.4.jar Backpacked {backpacked@1.2.0 DONE}
        betteranimalsplus-1.14.4-8.0.0.jar Better Animals Plus {betteranimalsplus@8.0.0 DONE}
        worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
        Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
        forge-1.14.4-28.2.1-universal.jar Forge {forge@28.2.1 DONE}
        Quark-r2.0-201.jar Quark {quark@r2.0-201 DONE}
        BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
        corpse-1.14.4-1.0.3.jar Corpse {corpse@1.14.4-1.0.3 DONE}
    Launched Version: forge-28.2.1
    LWJGL: 3.2.2 build 10
    OpenGL: NO CONTEXT
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
 
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'forge'
    Type: Client (map_client.txt)
    Resource Packs:
    Current Language: English (US)
    CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    OptiFine Version: OptiFine_1.14.4_HD_U_F5
    OptiFine Build: 20191204-141250
    Render Distance Chunks: 16
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.6.0 NVIDIA 419.67
    OpenGlRenderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

**Comment by Ferdzz** [comment]
Author of Placeable Items here. I was able to reproduce this crash https://github.com/Ferdzz/PlaceableItems/issues/77

@octarine-noise I wasn't able to find the source of the problem. I'm not sure if the problem is on my end or not. Could you please give this a quick look if possible? We don't do any custom rendering. I would appreciate your feedback & help fixing this compatibility issue :)

**Comment by ForsakenHarmony** [comment]
Same thing with bloomful https://www.curseforge.com/minecraft/mc-mods/bloomful

**Comment by MYSTRAVIL** [comment]
A similar crash caused by placing a Storage Drawer.
[2020-04-04-1.log](https://github.com/octarine-noise/BetterFoliage/files/4430192/2020-04-04-1.log)
