### ISSUE TITLE
Issue with Jukebox?

### ISSUE THREAD

**Issue by Ghost8909** [octarine-noise/BetterFoliage#290]
This one seems kind of weird, and I'm unsure how it's related to Better Foliage, but apparently it is?

I'm playing in a custom modpack. When I put a record into a jukebox and then remove it, the song keeps playing, and VanillaFix tells me Better Foliage ran into an issue.

Here's the [hastebin](https://hastebin.com/okiqoxuhel.rb) for the modpack, but also here's the [hastebin](https://paste.dimdev.org/uyilokofol.mccrash) for just Better Foliage and VanillaFix, just to show it's not any of my other mods.

I love Better Foliage, so I'd hate to have to remove it. I'm hoping it's just a Jukebox thing, as I rarely ever use one.

**Comment by jelle619** [comment]
I have exactly the same problem. Good to see I'm not the only one. I can confirm that disabling the mod through the Better Foliage config does not fix the issue. Only completely moving the mod fixes the issue.

It seems like somebody has already fixed the issue and is waiting for it to be merged: https://github.com/octarine-noise/BetterFoliage/pull/284/commits/ad233af235ef325bd7e2fa202930bfed5ecec8c4.

**Comment by TheQKnight** [comment]
Same issue here

**Comment by jelle619** [comment]
For anyone who is still experiencing this issue, it can temporarily be resolved by using the previous version of BetterFoliage.

**Comment by fkrisi11** [comment]
Having the same issue as well

**Comment by Gunner76th** [comment]
@Ghost8909 In the future please upload your crash reports directly as files. The 2 hastebin links you provided for your crash reports are dead/blank meaning those of us coming to research issues and confirm against reports cant. Just some friendly advise.

**Comment by Gunner76th** [comment]
@octarine-noise do you know how much longer before the update to resolve this issue will be released? The commit to fix this issue was done over 5 months ago, and yet the issue remains as the mod was not updated since Jan.

**Comment by geezerbahl** [comment]
Just ran into this issue today with the Engineer's Life modpack.  What caused mine - I had a jukebox with disc inserted but not playing music, and when I ejected the disc I got the following crash report.  

[crash-2020-07-10_19.00.57-client.txt](https://github.com/octarine-noise/BetterFoliage/files/4906140/crash-2020-07-10_19.00.57-client.txt)

**Comment by Ghost8909** [comment]
@Gunner76th Strange thing is, I could've sworn the hastebin I linked was the one generated by VanillaFix. 

Do those ever expire? Or maybe I just linked it wrong? Either way, I'll do that next time, thank you.

**Comment by SimplyProgrammer** [comment]
I have the same problem with 1.12.2 v2.3.1
I also get this exception when it happens:
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method mods.betterfoliage.client.chunk.ChunkOverlayManager.func_184377_a, parameter soundIn
at mods.betterfoliage.client.chunk.ChunkOverlayManager.func_184377_a(Overlay.kt) ~[ChunkOverlayManager.class:?]
at net.minecraft.world.World.func_184149_a(World.java:1142) ~[amu.class:?]
at net.minecraft.client.renderer.RenderGlobal.func_180439_a(RenderGlobal.java:3286) ~[buy.class:?]
com.ferreusveritas.dynamictrees.event.BlockBreakAnimationClientHandler$RenderGlobalWrapper.func_180439_a(BlockBreakAnimationClientHandler.java:297) ~[BlockBreakAnimationClientHandler$RenderGlobalWrapper.class:?]
at net.minecraft.world.World.func_180498_a(World.java:3709) ~[amu.class:?]
at net.minecraft.world.World.func_175718_b(World.java:3700) ~[amu.class:?]
at net.minecraft.client.network.NetHandlerPlayClient.func_147277_a(NetHandlerPlayClient.java:1401) ~[brz.class:?]
at net.minecraft.network.play.server.SPacketEffect.func_148833_a(SourceFile:45) ~[jf.class:?]
at net.minecraft.network.play.server.SPacketEffect.func_148833_a(SourceFile:10) ~[jf.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
... 9 more

**Comment by violettrin** [comment]
https://github.com/octarine-noise/BetterFoliage/issues/312 
@tappaja666 tappaja666 commented on Nov 10
If someone wants a fix for this problem, i compiled the pull request #284 wich fixes the problem. You can download it here https://www.dropbox.com/s/fvnzm1hhcgipuxy/BetterFoliage-MC1.12-2.3.1.jar?dl=1
