### ISSUE TITLE
[Crash][1.8.9] BetterFoliage-2.0.15 + SkyblockAddons-1.5.0-beta.17.jar + forge-11.15.1.2318 won't launch

### ISSUE THREAD

**Issue by TBlazeWarriorT** [octarine-noise/BetterFoliage#302]
[crash-2020-06-05_22.40.21-client.txt](https://github.com/octarine-noise/BetterFoliage/files/4739183/crash-2020-06-05_22.40.21-client.txt)
Crashes right after getting to the main menu due to "bad variable"

`java.lang.VerifyError: Bad local variable type
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Removing betterfoliage makes it stop crashing, so I believe it is directly related to betterfoliage.
Still crashes with default jvm args, it's not caused by my custom ones.

**Comment by NatureHog** [comment]
Just found this as well. I didn't know this was a general issue. Thanks!
