### ISSUE TITLE
[Forge 1.16.5] server crash

### ISSUE THREAD

**Issue by Krejzu** [octarine-noise/BetterFoliage#329]
This happens when trying to launch server

[17.05 10:50:07] [Server] 	Mod FileBetterFoliage-2.6.2-Forge-1.16.5.jar
[17.05 10:50:07] [Server] 	Failure messageBetter Foliage (betterfoliage) has failed to load correctly
[17.05 10:50:07] [Server] 		java.lang.ExceptionInInitializerErrornull
[17.05 10:50:07] [Server] 	Mod Version2.6.2
[17.05 10:50:07] [Server] 	Mod Issue URLhttps://github.com/octarine-noise/BetterFoliage/issues
[17.05 10:50:07] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[17.05 10:50:07] [Server] Stacktrace:
[17.05 10:50:07] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.18.jar:36.{}
[17.05 10:50:07] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
[17.05 10:50:07] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
[17.05 10:50:07] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
[17.05 10:50:07] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
[17.05 10:50:07] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
[17.05 10:50:07] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at mods.betterfoliage.BetterFoliageMod.<clinit>(BetterFoliageMod.kt:36) ~[betterfoliage:2.6.{re:classloading}
[17.05 10:50:07] [Server] 	at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117) ~[?:?] {re:classloading}
[17.05 10:50:07] [Server] 	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62) ~[?:?] {re:classloading}
[17.05 10:50:07] [Server] 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?] {re:classloading}
[17.05 10:50:07] [Server] 	at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt) ~[?:?] {re:classloading}
[17.05 10:50:07] [Server] 	at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242) ~[?:?] {re:classloading}
[17.05 10:50:07] [Server] 	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:102) ~[?:1.12.{re:classloading}
[17.05 10:50:07] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
[17.05 10:50:07] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_{}
[17.05 10:50:07] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_{}

**Comment by octarine-noise** [comment]
The shouldn't even try to load the mod, as it's marked as client-only, but maybe something else is interfering somehow... Idk.
Can you just remove the mod from the server?
