### ISSUE TITLE
Could not load to server

### ISSUE THREAD

**Issue by JueChenChen** [octarine-noise/BetterFoliage#353]
Mod File: [更好的树叶]BetterFoliage-2.6.5-Forge-1.16.5.jar
        Failure message: Better Foliage (betterfoliage) has failed to load correctly
                java.lang.ExceptionInInitializerError: null
        Mod Version: 2.6.5
        Mod Issue URL: https://github.com/octarine-noise/BetterFoliage/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.4.jar:36.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading,re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading,re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        at mods.betterfoliage.BetterFoliageMod.<clinit>(BetterFoliageMod.kt:74) ~[betterfoliage:2.6.5] {re:classloading}
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105) ~[?:?] {}
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1086) ~[?:?] {}
        at java.lang.reflect.Field.get(Field.java:418) ~[?:?] {}
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242) ~[?:?] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:102) ~[?:1.12.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by Big-Kuma** [comment]
Simple Fix: Delete the Mod from the server.

The mod is client-side, even though it shouldn't crash the server. Though since this is the case you can just delete it and everything should still work fine.
