### ISSUE TITLE
BYG compatibility crashes

### ISSUE THREAD

**Issue by Pure-Unadulterated-Balls** [octarine-noise/BetterFoliage#404]
Had a crash caused by oh the biomes youll go compatibility.  Heres the crash log:          ime: 10/18/21 6:55 PM
Description: Unexpected error

java.lang.ArithmeticException: / by zero
	at mods.betterfoliage.model.FixedSpriteSet.get(SpriteSets.kt:23) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.particle.FallingLeafParticle.<init>(FallingLeaves.kt:49) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.Hooks.onRandomDisplayTick(Hooks.kt:55) ~[?:2.7.1] {re:mixin,re:classloading}
	at net.minecraft.client.world.ClientWorld.handler$zcb000$onAnimateTick(ClientWorld.java:1204) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_184153_a(ClientWorld.java:511) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_73029_E(ClientWorld.java:500) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1526) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/36883680.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mods.betterfoliage.model.FixedSpriteSet.get(SpriteSets.kt:23) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.particle.FallingLeafParticle.<init>(FallingLeaves.kt:49) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.Hooks.onRandomDisplayTick(Hooks.kt:55) ~[?:2.7.1] {re:mixin,re:classloading}
	at net.minecraft.client.world.ClientWorld.handler$zcb000$onAnimateTick(ClientWorld.java:1204) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_184153_a(ClientWorld.java:511) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_73029_E(ClientWorld.java:500) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Jillfish261'/76, l='ClientLevel', x=93.99, y=64.00, z=513.47]]
	Chunk stats: Client Chunk Cache: 1369, 1023
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,71,208), Chunk: (at 0,4,0 in 1,13; contains blocks 16,0,208 to 31,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24213 game time, 35474 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/36883680.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1351112768 bytes (1288 MB) / 3019898880 bytes (2880 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 32
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.15.1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TerraForged-1.16.5-0.2.15.jar                     |TerraForged                   |terraforged                   |0.2.15              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		BetterFoliage-2.7.1-Forge-1.16.5.jar              |Better Foliage                |betterfoliage                 |2.7.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9b541460-7d8e-4688-b7a8-c559e6ad6a92
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.13, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 32x AMD Ryzen Threadripper 1950X 16-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs vibrant shaders
	OpenGlVersion: 4.6.0 NVIDIA 496.13
	OpenGlRenderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 32

**Comment by Pure-Unadulterated-Balls** [comment]
There was another crash after i turned off the connected grass as instructed by another post on this board. heres the log:
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at mods.betterfoliage.util.MethodRef.invoke(Reflection.kt:128) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardLeafModel.renderLayer(Leaf.kt:109) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.renderLayer(SpecialRenderModels.kt:47) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxVanilla$Companion.render(RenderCtxVanilla.kt:60) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxVanilla.render(RenderCtxVanilla.kt) ~[?:2.7.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.redirect$zca000$onRenderModelSmooth(BlockModelRenderer.java:616) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinBlockModelRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinBlockModelRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:915) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.optifine.mixins.json:MixinOptifineChunkRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:735) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.optifine.mixins.json:MixinOptifineChunkRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:192) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6814/661662248.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
	at net.optifine.shaders.SVertexBuilder.pushEntity(SVertexBuilder.java:48) ~[?:?] {re:classloading}
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at mods.betterfoliage.util.MethodRef.invoke(Reflection.kt:128) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardLeafModel.renderLayer(Leaf.kt:109) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.renderLayer(SpecialRenderModels.kt:47) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxVanilla$Companion.render(RenderCtxVanilla.kt:60) ~[?:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxVanilla.render(RenderCtxVanilla.kt) ~[?:2.7.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.redirect$zca000$onRenderModelSmooth(BlockModelRenderer.java:616) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinBlockModelRenderer,pl:mixin:A}
-- Block model being tesselated --
Details:
	Block: Block{minecraft:birch_leaves}[distance=2,persistent=false]
	Block location: World: (75,76,520), Chunk: (at 11,4,8 in 4,32; contains blocks 64,0,512 to 79,255,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinBlockModelRenderer,pl:mixin:A}


-- Block being tesselated --
Details:
	Block: Block{minecraft:birch_leaves}[distance=2,persistent=false]
	Block location: World: (75,76,520), Chunk: (at 11,4,8 in 4,32; contains blocks 64,0,512 to 79,255,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Jillfish261'/74, l='ClientLevel', x=93.99, y=64.00, z=513.47]]
	Chunk stats: Client Chunk Cache: 1369, 577
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,71,208), Chunk: (at 0,4,0 in 1,13; contains blocks 16,0,208 to 31,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24377 game time, 35638 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:198) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6820/1324573644.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2175903560 bytes (2075 MB) / 3724541952 bytes (3552 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 32
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.15.1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TerraForged-1.16.5-0.2.15.jar                     |TerraForged                   |terraforged                   |0.2.15              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		BetterFoliage-2.7.1-Forge-1.16.5.jar              |Better Foliage                |betterfoliage                 |2.7.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5c6f3c29-befd-4944-803b-9633df5a5958
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 32x AMD Ryzen Threadripper 1950X 16-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs vibrant shaders
	OpenGlVersion: 4.6.0 NVIDIA 496.13
	OpenGlRenderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 32
