### ISSUE TITLE
Game Crashes On Launch (Crash Report Within)

### ISSUE THREAD

**Issue by ghost** [octarine-noise/BetterFoliage#84]
Game crashes on launch, I've included the crash report below.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 9/4/16 12:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/octarinecore/Utils$sam$Supplier$d7953a9c
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mods/octarinecore/Utils$sam$Supplier$d7953a9c
    at mods.octarinecore.ThreadLocalDelegate.<init>(Utils.kt:50)
    at mods.betterfoliage.client.integration.OptifineCTM.<init>(OptifineCTM.kt:36)
    at mods.betterfoliage.client.integration.OptifineCTM.<clinit>(OptifineCTM.kt:23)
    at mods.betterfoliage.client.Client.<init>(Client.kt:63)
    at mods.betterfoliage.client.Client.<clinit>(Client.kt:27)
    at mods.betterfoliage.BetterFoliageMod.postInit(BetterFoliageMod.kt:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:577)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: mods.octarinecore.Utils$sam$Supplier$d7953a9c
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 43 more
Caused by: java.lang.NoClassDefFoundError: java/util/function/Supplier
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 45 more
Caused by: java.lang.ClassNotFoundException: java.util.function.Supplier
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 50 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Mac OS X (x86_64) version 10.11.3
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 192858856 bytes (183 MB) / 509911040 bytes (486 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJ   Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UCHIE   BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer

**Comment by octarine-noise** [comment]
You need to use Java 8
