### ISSUE TITLE
1.10.2 Client crash with version 2.1.1

### ISSUE THREAD

**Issue by bloodyraoul** [octarine-noise/BetterFoliage#89]
Description: Tesselating block in world

java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.world.ChunkCache.func_180494_b(ChunkCache.java:117)
    at ChunkCacheOF.func_180494_b(ChunkCacheOF.java:168)
    at CustomColors.getColorBiome(CustomColors.java:945)
    at CustomColors$5.getColor(CustomColors.java:204)
    at CustomColors.getSmoothColorMultiplier(CustomColors.java:1002)
    at CustomColors.getFluidColor(CustomColors.java:1041)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(BlockFluidRenderer.java:59)
    at team.chisel.client.render.BlockRendererDispatcherWrapper.func_175018_a(BlockRendererDispatcherWrapper.java:65)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:97)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.world.ChunkCache.func_180494_b(ChunkCache.java:117)
    at ChunkCacheOF.func_180494_b(ChunkCacheOF.java:168)
    at CustomColors.getColorBiome(CustomColors.java:945)
    at CustomColors$5.getColor(CustomColors.java:204)
    at CustomColors.getSmoothColorMultiplier(CustomColors.java:1002)
    at CustomColors.getFluidColor(CustomColors.java:1041)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(BlockFluidRenderer.java:59)

-- Block being tesselated --
Details:
    Block type: ID #9 (tile.water // net.minecraft.block.BlockStaticLiquid)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-977,48,-288), Chunk: (at 15,3,0 in -62,-18; contains blocks -992,0,-288 to -977,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
Stacktrace:
    at team.chisel.client.render.BlockRendererDispatcherWrapper.func_175018_a(BlockRendererDispatcherWrapper.java:65)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:97)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['bloodyraoul'/172635, l='MpServer', x=-999.50, y=130.00, z=-399.50]]
    Chunk stats: MultiplayerChunkCache: 185, 185
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,80,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 117597 game time, 117597 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
    Forced entities: 44 total; [EntityPlayerSP['bloodyraoul'/172635, l='MpServer', x=-999.50, y=130.00, z=-399.50], EntityMinecartChest['Minecart with Chest'/173394, l='MpServer', x=-929.50, y=22.06, z=-140.50], EntityRabbit['Rabbit'/172642, l='MpServer', x=-719.79, y=78.00, z=940.21], EntityItem['item.tile.seaweed'/173474, l='MpServer', x=-1029.98, y=31.00, z=-431.03], EntityItem['item.tile.sand.default'/173475, l='MpServer', x=-1030.52, y=27.00, z=-430.43], EntityItem['item.tile.seaweed'/173472, l='MpServer', x=-1028.16, y=26.00, z=-431.33], EntityItem['item.tile.seaweed'/173473, l='MpServer', x=-1027.82, y=26.00, z=-429.12], EntityItem['item.tile.seaweed'/173478, l='MpServer', x=-1024.08, y=31.00, z=-428.03], EntityItem['item.tile.seaweed'/173476, l='MpServer', x=-1030.18, y=30.00, z=-429.55], EntityItem['item.tile.mushroom.glowshroom'/173477, l='MpServer', x=-1030.68, y=27.00, z=-430.88], EntityItem['item.tile.seaweed'/173526, l='MpServer', x=-1022.29, y=26.00, z=-434.62], EntityItem['item.tile.seaweed'/173527, l='MpServer', x=-1022.85, y=27.00, z=-436.75], EntityItem['item.tile.seaweed'/173525, l='MpServer', x=-1022.39, y=31.00, z=-437.73], EntityItem['item.tile.seaweed'/173530, l='MpServer', x=-1020.43, y=26.00, z=-435.00], EntityItem['item.tile.seaweed'/173531, l='MpServer', x=-1021.30, y=28.00, z=-433.90], EntityItem['item.tile.seaweed'/173528, l='MpServer', x=-1021.26, y=26.00, z=-435.11], EntityItem['item.tile.seaweed'/173529, l='MpServer', x=-1023.06, y=26.00, z=-435.24], EntityItem['item.tile.seaweed'/173534, l='MpServer', x=-966.06, y=25.00, z=-437.91], EntityItem['item.tile.seaweed'/173535, l='MpServer', x=-965.13, y=25.00, z=-442.88], EntityItem['item.tile.seaweed'/173532, l='MpServer', x=-1023.81, y=26.00, z=-435.88], EntityItem['item.tile.kelp'/173533, l='MpServer', x=-962.89, y=28.00, z=-437.42], EntityItem['item.tile.seaweed'/173538, l='MpServer', x=-962.95, y=29.00, z=-433.68], EntityItem['item.tile.seaweed'/173539, l='MpServer', x=-963.82, y=27.00, z=-432.17], EntityItem['item.tile.seaweed'/173536, l='MpServer', x=-963.47, y=28.00, z=-433.93], EntityItem['item.tile.seaweed'/173537, l='MpServer', x=-973.34, y=28.00, z=-439.13], EntityItem['item.tile.seaweed'/173542, l='MpServer', x=-965.96, y=26.00, z=-435.04], EntityItem['item.tile.kelp'/173543, l='MpServer', x=-962.33, y=26.00, z=-439.65], EntityItem['item.tile.seaweed'/173540, l='MpServer', x=-967.10, y=27.00, z=-433.77], EntityItem['item.tile.seaweed'/173541, l='MpServer', x=-962.70, y=24.00, z=-440.13], EntityItem['item.tile.seaweed'/173546, l='MpServer', x=-968.25, y=31.00, z=-433.41], EntityItem['item.tile.seaweed'/173547, l='MpServer', x=-967.88, y=26.00, z=-439.62], EntityItem['item.tile.seaweed'/173544, l='MpServer', x=-966.34, y=26.00, z=-441.56], EntityItem['item.tile.seaweed'/173545, l='MpServer', x=-975.08, y=31.00, z=-440.02], EntityItem['item.tile.seaweed'/173550, l='MpServer', x=-961.44, y=25.00, z=-441.40], EntityItem['item.tile.seaweed'/173551, l='MpServer', x=-964.27, y=26.00, z=-433.26], EntityItem['item.tile.seaweed'/173548, l='MpServer', x=-966.94, y=25.00, z=-436.83], EntityItem['item.tile.seaweed'/173549, l='MpServer', x=-963.14, y=26.00, z=-443.23], EntityItem['item.tile.seaweed'/173554, l='MpServer', x=-966.16, y=27.00, z=-432.59], EntityItem['item.tile.seaweed'/173555, l='MpServer', x=-974.49, y=31.00, z=-438.98], EntityItem['item.tile.seaweed'/173552, l='MpServer', x=-965.52, y=25.00, z=-435.89], EntityItem['item.tile.seaweed'/173553, l='MpServer', x=-973.36, y=27.00, z=-441.85], EntityItem['item.tile.seaweed'/173558, l='MpServer', x=-959.87, y=27.00, z=-441.10], EntityItem['item.tile.torch'/173556, l='MpServer', x=-953.27, y=23.00, z=-459.44], EntityItem['item.tile.seaweed'/173557, l='MpServer', x=-959.60, y=28.00, z=-439.51]]
    Retry entities: 17 total; [EntityRabbit['Rabbit'/172642, l='MpServer', x=-719.79, y=78.00, z=940.21], EntityItem['item.tile.flower2.poppy'/173408, l='MpServer', x=-990.37, y=12.00, z=-171.84], EntityRabbit['Rabbit'/172641, l='MpServer', x=-721.50, y=79.00, z=938.50], EntityItem['item.tile.flower1.dandelion'/173409, l='MpServer', x=-995.88, y=13.00, z=-174.13], EntityCar1['entity.frsm.Car1.name'/172710, l='MpServer', x=-799.50, y=74.00, z=921.50], EntityItem['item.tile.flower2.poppy'/173420, l='MpServer', x=-1037.88, y=13.00, z=-141.88], EntityMinecartChest['Minecart with Chest'/173394, l='MpServer', x=-929.50, y=22.06, z=-140.50], EntityItem['item.tile.flower2.poppy'/173427, l='MpServer', x=-997.83, y=13.00, z=-176.17], EntityCar1['entity.frsm.Car1.name'/172785, l='MpServer', x=-782.50, y=96.00, z=1075.50], EntityCar1['entity.frsm.Car1.name'/172662, l='MpServer', x=-802.50, y=73.00, z=922.50], EntityItem['item.item.rock.diorite'/173428, l='MpServer', x=-997.88, y=13.00, z=-176.13], EntityCar1['entity.frsm.Car1.name'/172661, l='MpServer', x=-803.50, y=73.00, z=921.50], EntityItem['item.item.seeds'/173429, l='MpServer', x=-1038.16, y=13.00, z=-145.77], EntityItem['item.item.plant_fiber'/173406, l='MpServer', x=-990.78, y=12.00, z=-171.22], EntityItem['item.tile.flower1.dandelion'/173407, l='MpServer', x=-988.34, y=12.00, z=-170.94], EntityItem['item.tile.terraqueous.plants.cactus'/172637, l='MpServer', x=-744.54, y=66.00, z=980.09], EntityItem['item.item.seeds'/173405, l='MpServer', x=-984.18, y=11.00, z=-173.66]]
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
    at java.lang.Thread.run(Thread.java:745)

**Comment by bloodyraoul** [comment]
Maybe it is not a better foliage crash but Chisel
it is very similar to this bug : https://github.com/Chisel-Team/Chisel/issues/241
I let you examine and close if needed
